const BT_YH = {
	// 连接认证
	DEVIDES_AUTH: {
		COMMAND: "YH_A_2685_END",
		D_COMMAND: "YH_D_A_",
		D_S_COMMAND: "YH_D_A_SUCCESS_END",
		D_F_COMMAND: "YH_D_A_FAIL_END"
	},
	// 设置闹钟
	DEVIDES_SET: {
		COMMAND: "YH_SET",
		D_COMMAND: "YH_D_SET_",
		D_S_COMMAND: "YH_D_SET_SUCCESS_END",
		D_F_COMMAND: "YH_D_SET_FAIL_END"
	},
	// 同步时间
	DEVIDES_TIME: {
		COMMAND: "YH_TIME",
		D_COMMAND: "YH_D_TIME_SYNC_END",
		D_S_COMMAND: "YH_D_TIME_SUCCESS_END",
		D_F_COMMAND: "YH_D_TIME_FAIL_END"
	},
	// 删除药盒提醒记录
	DEVIDES_CLR: {
		COMMAND: "YH_CLR",
		ALL_COMMAND: "YH_CLR_ALL_END",
		D_COMMAND: "YH_D_CLR_",
		D_S_COMMAND: "YH_D_CLR_SUCCESS_END",
		D_F_COMMAND: "YH_D_CLR_FAIL_END"
	},
	// 闹铃上载
	UP_ALARM: {
		COMMAND: "YH_UP_ALARM_END", // 请求指令
		D_UP_DATA_COMMAND: "YH_D_UP_ALARM_", // 上传的数据指令
		D_START_COMMAND: "YH_D_UP_", // 上传的开始指令
		D_OVER_COMMAND: "YH_D_UP_OVER_END", // 上传结束指令
		D_F_COMMAND: "YH_D_UP_FAIL_END" // 上传失败指令
	},
	// 用药记录
	HISTORY_TM: {
		D_COMMAND: "YH_D_TM",
		S_COMMAND: "YH_TM_SUCCESS_END",
		F_COMMAND: "YH_TM_FAIL_END"
	},
	// 药盒搜寻打开
	DEVIDES_SEARCH_OPEN: {
		COMMAND: "YH_SEARCH_OPEN_END",
		D_COMMAND: "YH_D_SEARCH_OPEN_",
		D_S_COMMAND: "YH_D_SEARCH_OPEN_SUCCESS_END",
		D_F_COMMAND: "YH_D_SEARCH_OPEN_FAIL_END"
	},
	// 药盒搜寻关闭
	DEVIDES_SEARCH_CLOSE: {
		COMMAND: "YH_SEARCH_CLOSE_END",
		D_COMMAND: "YH_D_SEARCH_CLOSE_",
		D_S_COMMAND: "YH_D_SEARCH_CLOSE_SUCCESS_END",
		D_F_COMMAND: "YH_D_SEARCH_CLOSE_FAIL_END"
	},
	// 设置药盒音量
	DEVIDES_VOLUME: {
		COMMAND: "YH_VOLUME", //设置音量
		D_COMMAND: "YH_D_VOLUME_",
		D_S_COMMAND: "YH_D_VOLUME_SUCCESS_END", // 接收成功指令
		D_F_COMMAND: "YH_D_VOLUME_FAIL_END" // 接收失败指令
	},
	// 获取药盒音量
	QUERY_VOLUME: {
		COMMAND: "YH_QUERY_VOLUME_END", //获取音量
		D_COMMAND: "YH_D_QUERY_VOLUME_",
		D_S_COMMAND: "YH_D_QUERY_VOLUME_", // 接收成功指令
		D_F_COMMAND: "YH_D_QUERY_VOLUME_FAIL_END" // 接收失败指令
	},
	// 获取版本号
	VERSION: {
		COMMAND: "YH_VERSION_END", //版本号获取
		D_COMMAND: "YH_D_VERSION_",
		D_S_COMMAND: "YH_D_VERSION_", // 接收成功指令
		D_F_COMMAND: "YH_D_VERSION_FAIL_END" // 接收失败指令
	}
}

export default BT_YH